version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=75waychatserver
      - PORT=4000
    depends_on:
      - mysql
    networks:
      - node
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=backend
    ports:
      - "3306:3306"  # Maps 5432 on host to 3306 (default MySQL port) in container
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - node
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  node:
    driver: bridge
